server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 115.190.12.119:8848
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: interface
          uri: lb://openapi-interface
          predicates:
            - Path=/interface/**

        - id: provider-interface
          uri: lb://openapi-provider-interface
          predicates:
            - Path=/provider/**

        - id: permission
          uri: lb://openapi-permission
          predicates:
            - Path=/permission/**

        - id: system
          uri: lb://openapi-system
          predicates:
            - Path=/system/**

        - id: order
          uri: lb://openapi-order
          predicates:
            - Path=/lines/**

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 140.143.159.190
    password: 123456
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0