server:
  port: 9006

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 115.190.12.119:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.190.9.34:3306/open-api?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 'swx020708'

mybatis-plus:
  type-enums-package: open.api.enums

#支付宝配置
# 说明：长时间不用的商户账号会失效，如果报商户协议xxx，基本就是这个原因
# 解决办法：前往商户平台：https://b.alipay.com/page/portal/home
# 找到消息列表的系统消息，按照要求重新提交商户信息即可
alipay:
  appId: "ddddddddddddd"
  privateKey: "xxxxxxxxxxxxxx"
  alipayPublicKey: "uyyyyyyyyyyyy"
  serverUrl: "ssssssssssssss"

#knife4j
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin