server:
  port: 9001

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open-api?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '020708'

mybatis-plus:
  type-enums-package: open.api.enums

#knife4j
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin

#系统日志配置
logging:
  level:
    open:
      api:
        controller: info
  file:
    name: D:\\logging\\${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB

#自定义starter配置
open:
  api:
    access-key: 645afd75e5037c3e21c50887cae0914a
    secret-key: 80afae201db7ed5a8388150e7ebc573d
